# Gerrit開発者定着予測システム - メイン設定ファイル

# Gerrit接続設定
gerrit:
  url: "https://gerrit.example.com" # デフォルト値、環境変数で上書き可能
  auth:
    username: "" # 環境変数で設定
    password: "" # 環境変数で設定
  projects:
    - "project-a"
    - "project-b"

  # データ抽出設定
  data_extraction:
    batch_size: 1000
    rate_limit_delay: 1.0 # seconds
    max_retries: 3
    timeout: 30 # seconds

# ログ設定
logging:
  level: "INFO" # 環境変数で上書き可能
  format: "text" # 環境変数で上書き可能
  file: "" # 環境変数で設定

# 機械学習設定
ml:
  random_seed: 42 # 環境変数で上書き可能
  device: "auto" # auto, cpu, cuda

# 定着予測設定
retention_prediction:
  model_type: "random_forest"
  model_params:
    n_estimators: 100
    max_depth: 10
    random_state: 42

  # Gerrit特有の特徴量
  gerrit_features:
    use_review_scores: true
    use_response_times: true
    use_change_complexity: true
    use_collaboration_network: true

# ストレス分析設定
stress_analysis:
  weights:
    review_compatibility_stress: 0.3
    workload_stress: 0.4
    social_stress: 0.2
    temporal_stress: 0.1

  # Gerrit特有のストレス要因
  gerrit_stress_factors:
    high_complexity_threshold: 0.8
    review_queue_size_threshold: 5
    response_time_pressure_threshold: 24 # hours

# 強化学習環境設定
rl_environment:
  observation_space_dim: 20
  action_space_size: 3 # accept, decline, defer
  max_episode_length: 100

  reward_weights:
    acceptance_reward: 1.0
    decline_penalty: -0.5
    defer_penalty: -0.1
    continuity_bonus: 0.3
    stress_factor: 0.2
    quality_bonus: 0.1
    collaboration_bonus: 0.15

  # Gerrit特有の報酬設計
  gerrit_rewards:
    high_quality_review_bonus: 0.2 # +2スコアのレビュー
    thorough_review_bonus: 0.1
    quick_response_bonus: 0.05

# PPOエージェント設定
ppo_agent:
  policy_lr: 3e-4
  value_lr: 3e-4
  clip_epsilon: 0.2
  gamma: 0.99
  gae_lambda: 0.95
  batch_size: 64
  n_epochs: 10

# 時系列整合性設定
temporal_consistency:
  enable_strict_validation: true
  train_end_date: "2022-12-31"
  test_start_date: "2023-01-01"

  # Gerrit特有の時系列設定
  gerrit_temporal:
    review_history_window: 90 # days
    developer_profile_update_frequency: 7 # days
    stress_calculation_window: 14 # days

# 可視化設定
visualization:
  output_dir: "outputs/visualizations"
  figure_format: "png"
  figure_dpi: 300
  color_scheme: "viridis"

# キャッシュ設定
cache:
  enabled: true # 環境変数で上書き可能
  ttl: 3600 # seconds
  backend: "memory" # memory, redis

# 実験追跡設定
experiment_tracking:
  enabled: false
  backend: "mlflow" # mlflow, wandb
  experiment_name: "gerrit-retention-prediction"
