# IRL Feature Registry (Phase1 incremental)
# status: experimental -> active -> deprecated
features:
  - name: activity7
    phase: 1
    status: experimental
    description: Count of reviewer transitions in past 7 days (exclusive of current timestamp)
    requires: [transitions]
    leakage_guard: timestamp_window
    type: count
    fallback: 0
  - name: workload_sq
    phase: 1
    status: experimental
    description: Square of workload feature to capture overload curvature
    requires: [state.workload]
    leakage_guard: none
    type: numeric
    derived_from: workload
  - name: reviewer_tenure_days
    phase: 1
    status: experimental
    description: Days since first seen transition for reviewer (capped at 2000)
    requires: [transitions]
    leakage_guard: historical_cutoff
    type: duration
    fallback: 0
  - name: interaction_activity_gap
    phase: 1
    status: experimental
    description: activity30 / (1 + gap_days) interaction emphasizing recent non-idle activity
    requires: [state.activity30, state.gap_days]
    leakage_guard: none
    type: numeric
    derived_from: [activity30, gap_days]
  # Placeholders for later phases (not computed yet)
  - name: backlog_open_reviews
    phase: 1
    status: experimental
    description: Approx open reviews count (state.open_reviews if available else workload*activity30 heuristic)
  - name: historical_accept_ratio
    phase: 1
    status: experimental
    description: Accepted transitions / all transitions before timestamp (capped, min denom=3)
  - name: avg_response_latency_hours
    phase: 1
    status: pending
    description: Average hours from assignment to first response (log1p inverse recommended)
  - name: owner_reviewer_past_assignments_180d
    phase: 1
    status: experimental
    description: Past 180d assignments between owner and reviewer (requires owner id in sequence)
  - name: path_tfidf_cosine_recent30
    phase: 1
    status: experimental
    description: Improved TF-IDF cosine (dir1+dir2 tokens, normalized TF, 30d window)
  - name: active_hour_match
    phase: 1
    status: experimental
    description: 1 if current hour within top frequent active hours (last 30d) for reviewer
  - name: path_jaccard_dir2_180d
    phase: 2
    status: experimental
    description: Jaccard similarity of dir2 path segments between current change and reviewer history (<=180d)
  - name: path_overlap_count_dir2_180d
    phase: 2
    status: experimental
    description: Count of overlapping dir2 tokens between change paths and reviewer history (<=180d)
    type: count
    requires: [change.files, reviewer.history.paths]
  - name: path_overlap_ratio_dir2_180d
    phase: 2
    status: experimental
    description: Overlap count normalised by change dir2 token count
    type: ratio
    derived_from: [path_overlap_count_dir2_180d, change_secondary_dir_count]
  - name: path_overlap_recent30
    phase: 2
    status: experimental
    description: Sum of reviewer path hits for current change tokens within last 30 days
    type: count
    requires: [change.files, reviewer.history.paths]
  - name: owner_reviewer_past_assignments_180d_log1p
    phase: 2
    status: experimental
    description: log1p of past 180d assignments between owner and reviewer
  - name: owner_reviewer_past_assignments_ratio_180d
    phase: 2
    status: experimental
    description: Ratio (pair_count / total_reviewer_assignments_180d)
  # Task-scoped (change-level) features derived from Gerrit metadata
  - name: change_file_count
    phase: 1
    status: experimental
    description: Number of files touched by the change
    type: count
    requires: [change.files]
  - name: change_file_count_log1p
    phase: 1
    status: experimental
    description: log1p of file count for diminishing returns
    type: numeric
    derived_from: change_file_count
  - name: change_insertions
    phase: 1
    status: experimental
    description: Raw insertion count reported by Gerrit for the change
    type: numeric
    requires: [change.insertions]
  - name: change_insertions_log1p
    phase: 1
    status: experimental
    description: log1p(insertions) to dampen large changes
    type: numeric
    derived_from: change_insertions
  - name: change_deletions
    phase: 1
    status: experimental
    description: Raw deletion count reported by Gerrit for the change
    type: numeric
    requires: [change.deletions]
  - name: change_deletions_log1p
    phase: 1
    status: experimental
    description: log1p(deletions) to dampen large changes
    type: numeric
    derived_from: change_deletions
  - name: change_churn_per_file
    phase: 1
    status: experimental
    description: Average churn per file (total churn / max(1, file_count))
    type: numeric
    derived_from: [change_total_churn, change_file_count]
  - name: change_primary_dir_count
    phase: 1
    status: experimental
    description: Number of unique top-level directories touched by the change
    type: count
    requires: [change.files]
  - name: change_secondary_dir_count
    phase: 1
    status: experimental
    description: Number of unique second-level directory prefixes (dir1/dir2 tokens)
    type: count
    requires: [change.files]
  - name: change_primary_dir_max_frac
    phase: 1
    status: experimental
    description: Largest share of files belonging to a single top-level directory (0-1)
    type: numeric
    derived_from: change.files
  - name: change_total_churn
    phase: 1
    status: experimental
    description: Total churn (insertions + deletions) reported by Gerrit for the change
    type: numeric
    requires: [change.insertions, change.deletions]
  - name: change_total_churn_log1p
    phase: 1
    status: experimental
    description: log1p(total churn) for scale compression
    type: numeric
    derived_from: change_total_churn
  - name: change_doc_file_ratio
    phase: 1
    status: experimental
    description: Fraction of files under documentation-related paths
    type: ratio
    requires: [change.files]
  - name: change_test_file_ratio
    phase: 1
    status: experimental
    description: Fraction of files under test-related paths
    type: ratio
    requires: [change.files]
  - name: change_avg_path_depth
    phase: 1
    status: experimental
    description: Average path depth (segments) across change files
    type: numeric
    requires: [change.files]
  - name: change_max_path_depth
    phase: 1
    status: experimental
    description: Maximum path depth observed across change files
    type: numeric
    requires: [change.files]
  - name: change_subject_length
    phase: 1
    status: experimental
    description: Length of change subject string in characters
    type: numeric
    requires: [change.subject]
  - name: change_subject_length_log1p
    phase: 1
    status: experimental
    description: log1p of subject length to dampen long tails
    type: numeric
    derived_from: change_subject_length
  - name: change_subject_word_count
    phase: 1
    status: experimental
    description: Number of tokens in change subject (split on whitespace)
    type: count
    requires: [change.subject]
  - name: change_is_revert
    phase: 1
    status: experimental
    description: 1 if subject starts with "Revert" (indicates fix-up work)
    type: binary
    requires: [change.subject]
  - name: change_topic_length
    phase: 1
    status: experimental
    description: Number of whitespace-separated tokens in Gerrit topic (if set)
    type: count
    requires: [change.topic]
