# IRL Feature Registry (Phase1 incremental)
# status: experimental -> active -> deprecated
features:
  - name: activity7
    phase: 1
    status: experimental
    description: Count of reviewer transitions in past 7 days (exclusive of current timestamp)
    requires: [transitions]
    leakage_guard: timestamp_window
    type: count
    fallback: 0
  - name: workload_sq
    phase: 1
    status: experimental
    description: Square of workload feature to capture overload curvature
    requires: [state.workload]
    leakage_guard: none
    type: numeric
    derived_from: workload
  - name: reviewer_tenure_days
    phase: 1
    status: experimental
    description: Days since first seen transition for reviewer (capped at 2000)
    requires: [transitions]
    leakage_guard: historical_cutoff
    type: duration
    fallback: 0
  - name: interaction_activity_gap
    phase: 1
    status: experimental
    description: activity30 / (1 + gap_days) interaction emphasizing recent non-idle activity
    requires: [state.activity30, state.gap_days]
    leakage_guard: none
    type: numeric
    derived_from: [activity30, gap_days]
  # Phase 1+ extended features (non change-level)
  - name: avg_response_latency_hours
    phase: 1
    status: pending
    description: Average hours from assignment to first response (log1p inverse recommended)
  - name: owner_reviewer_past_assignments_180d
    phase: 1
    status: experimental
    description: Past 180d assignments between owner and reviewer (requires owner id in sequence)
  - name: path_overlap_ratio_dir2_180d
    phase: 2
    status: experimental
    description: Dir2 token overlap ratio between current change paths and reviewer history (<=180d)
    type: ratio
  - name: owner_reviewer_past_assignments_180d_log1p
    phase: 2
    status: experimental
    description: log1p of past 180d assignments between owner and reviewer
  - name: owner_reviewer_past_assignments_ratio_180d
    phase: 2
    status: experimental
    description: Ratio (pair_count / total_reviewer_assignments_180d)
