# API サーバー設定ファイル
server:
  host: "0.0.0.0"
  port: 8080
  reload: false
  workers: 1

cors:
  allow_origins: ["*"]
  allow_credentials: true
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allow_headers: ["*"]

models:
  retention:
    path: "models/retention_model.pkl"
    type: "sklearn"
    enabled: true
  stress:
    path: "models/stress_model.pkl"
    type: "sklearn"
    enabled: true
  ppo:
    path: "models/ppo_agent.zip"
    type: "stable_baselines3"
    enabled: true

defaults:
  satisfaction_level: 0.7
  confidence_threshold: 0.5
  max_request_size: 10485760 # 10MB
  request_timeout: 30 # seconds

security:
  rate_limit:
    enabled: true
    requests_per_minute: 60
  api_key:
    enabled: false
    header_name: "X-API-Key"

monitoring:
  metrics_enabled: true
  health_check_enabled: true
  request_logging: true
