services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
        USERNAME: ${USERNAME:-vscode}
    container_name: ${COMPOSE_PROJECT_NAME:-docker-template}
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
    volumes:
      - type: bind
        source: .
        target: /home/${USERNAME:-vscode}/workspace
    stdin_open: true
    tty: true
    command: /bin/bash